services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CoreShop\Component\Resource\TokenGenerator\JWTGenerator:
    arguments:
      $privateKeyPath: '%jwt_private_key_path%'
      $customerTokenLifetimeInSeconds: 3600 # 60 * 60 seconds
      $backendTokenLifetimeInSeconds: 300 # 5 * 60 seconds Set short as possible!!!

  # TODO: This is just a guideline. Configure correctly.
